### ISSUE TITLE
Richtext not working when index is set to instance

### ISSUE THREAD

**Issue by CheeseDabber** [PysephWasntAvailable/PacketProfiler#7]
![image](https://github.com/Pyseph/PacketProfiler/assets/94117434/f96678b7-ae8c-4b62-8dc7-fd6cc80a56ef)
I don't know how this happened but as you can see all the font colors aren't working in the plugin.

EDIT: Having the same problem with the in game version as well although weirdly enough richtext is enabled on the textlabel.

ANOTHER EDIT: I found the issue. I had an index set to an instance and that has characters which breaks the richtext

**Comment by Pyseph** [comment]
Hi! do you have the specific name used which broke it?

EDIT: I found a repro myself. All good!

**Comment by Pyseph** [comment]
this has been fixed as of v2.0.0.
